AutoShow/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShow.Data;
using AutoShow.Models;
using AutoShow.Models.Implementations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutoShow.Controllers
{
    [Authorize(Roles ="Admin")]
    public class BrandController : Controller
    {
        private BrandOperation brandOperation;

        public BrandController(VehicleDbContext vehicleDbContext)
        {
            brandOperation = new BrandOperation(vehicleDbContext);
        }

        public async Task<IActionResult> Index()
        {
            return View(await brandOperation.Read());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Name")]Brand brand)
        {
            if(ModelState.IsValid)
            {
                bool check=await brandOperation.Create(brand);
                if (check)
                    return View(nameof(Index));
            }
            return View();
        }

    }
}

AutoShow/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShow.Data;
using AutoShow.Models.Implementations;
using Microsoft.AspNetCore.Mvc;

namespace AutoShow.Controllers
{
    public class UserController : Controller
    {
        private UserOperation userOperation;

        public UserController(VehicleDbContext vehicleDbContext)
        {
            userOperation = new UserOperation(vehicleDbContext);
        }

        public async Task<IActionResult> Index()
        {
            return View(await userOperation.Read());
        }

        public async Task<IActionResult> Detail(string id)
        {
            if (id == "")
                return NotFound();

            return View(await userOperation.Detail(id));
        }
    }
}

AutoShow/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShow.Data;
using AutoShow.Models;
using AutoShow.Models.Implementations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AutoShow.Controllers
{
    [Authorize(Roles ="Admin,User")]
    public class VehicleController : Controller
    {
        private VehicleOperation vehicleOperation;
        private readonly UserManager<ApplicationUser> userManager;

        public VehicleController(VehicleDbContext vehicleDbContext,UserManager<ApplicationUser> userManager)
        {
            vehicleOperation = new VehicleOperation(vehicleDbContext);
            this.userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await vehicleOperation.Read());
        }

        [AllowAnonymous]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
                return NotFound();

            var vehicle =await vehicleOperation.Detail(id.ToString());

            if (vehicle == null)
                return NotFound();

            return View(vehicle);
        }

        public IActionResult Add()
        {
            ViewData["Brands"] = new SelectList(vehicleOperation.GetBrand(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Name,Type,Price,Colour,BrandId")] Vehicle vehicle)
        {
            var asd = userManager.GetUserId(HttpContext.User);
            if (asd == null)
                return NotFound();
            vehicle.ApplicationUserId = asd;
            if (ModelState.IsValid)
            {
                bool check = false;
                check = await vehicleOperation.Create(vehicle);
                if (check)
                    return RedirectToAction(nameof(Index));
            }
            ViewData["Brands"] = new SelectList(vehicleOperation.GetBrand(), "Id", "Name", vehicle.BrandId);
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var vehicle = vehicleOperation.Search(id.ToString());

            if (vehicle == null)
                return NotFound();

            ViewData["Brands"] = new SelectList(vehicleOperation.GetBrand(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id,[Bind("Name,Type,Price,Colour,BrandId")]Vehicle vehicle)
        {
            if (vehicle.Id != id)
                return NotFound();

            if(ModelState.IsValid)
            {
                bool check=await vehicleOperation.Edit(vehicle);
                if (check)
                    return RedirectToAction(nameof(Index));
            }
            ViewData["Brands"] = new SelectList(vehicleOperation.GetBrand(), "Id", "Name");
            return View();
        }

        public async  Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var vehicle =await vehicleOperation.Detail(id.ToString());

            if (vehicle == null)
                return NotFound();

            return View(vehicle);
        }

        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async  Task<IActionResult> DeleteConfirm(int? id)
        {
            bool check =await vehicleOperation.Delete(id.ToString());
            if (check)
                return RedirectToAction(nameof(Index));
            return View();
        }

    }
}

AutoShow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoShow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top bg-transparent" style="z-index:5;">
            <div class="navbar-brand">
                <a asp-action="Index" asp-controller="Home">AutoShow</a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navSupportContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse justify-content-end">
                <ul class="navbar-nav text-white">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Vehicle" asp-action="Index">Vehicle</a>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Brand" asp-action="Index">Brands</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="User" asp-action="Index">Users</a>
                    </li>
                    }
                    <partial name="_LoginPartial" />
                </ul>
                <form class="form-inline d-inline-flex" method="post" href="http://google.com/">
                    <input class="form-control OneLine" placeholder="Search" />
                    <button type="submit" class="bg-transparent p-1 border-0"><i class="fa fa-search" style="font-size:20px;color:white"></i></button>
                </form>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
                @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AutoShow - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>